/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./components/**/*.{js,jsx,ts,tsx,html}",
    "./app/**/*.{js,jsx,ts,tsx,html}",
    "./src/**/*.{js,jsx,ts,tsx,html}",
    "!./.history/**/*",
  ],
  theme: {
    extend: {
      colors: {
        light: {
          bg: {
            primary: "#FFFFFF",
            secondary: "#F6F8FA",
            tertiary: "#F6F8FA",
            quartiary: "#DEE1E5",
            button: "#F6F8FA",
            hover: "#EAEDF0",
          },
          accent: {
            border: "#D1D9E0",
            active: "#FD8C73",
            icon: "#59636E",
            extra: "#0969DA",
            extraBorder: "#0D5EC0",
          },
          text: {
            primary: "#1F2328",
            secondary: "#6B747E",
            link: "#4493F8",
          },
          other: {
            chartSquare: "#ebedf0",
            green1: "#0be9a8",
            green2: "#40c463",
            green3: "#30a14e",
            green4: "#216e39",
            blue1: "#339af0",
            blue2: "#007bff",
            blue3: "#0056b3",
            blue4: "#003f88",
            purple1: "#9370db",
            purple2: "#8a2be2",
            purple3: "#6a0dad",
            purple4: "#4b0082",
            orange1: "#ffc066",
            orange2: "#ffa940",
            orange3: "#ff8c1a",
            orange4: "#ff6f00",
            red1: "#ffcdd2",
            red2: "#ef9a9a",
            red3: "#e57373",
            red4: "#f44336",
            yellow1: "#dad07b",
            yellow2: "#fae84b",
            yellow3: "#ecd718",
            yellow4: "#ceba0c",
          },
        },
        dark: {
          bg: {
            primary: "#0D1117",
            secondary: "#010409",
            tertiary: "#151B23",
            quartiary: "#15191F",
            button: "#212830",
            hover: "#15191F",
          },
          accent: {
            border: "#2F353D",
            active: "#F78166",
            icon: "#9198A1",
            extra: "#238636",
          },
          text: {
            primary: "#F0F6FC",
            secondary: "#858C95",
            link: "#4493F8",
          },
          other: {
            chartSquare: "#161b22",
            green1: "#034429",
            green2: "#006d32",
            green3: "#26a641",
            green4: "#39d353",
            blue1: "#1e3a73",
            blue2: "#2c549f",
            blue3: "#3b6be4",
            blue4: "#4e88ff",
            purple1: "#6c5491",
            purple2: "#8f6bb5",
            purple3: "#aa88d3",
            purple4: "#caa3ff",
            orange1: "#b3741f",
            orange2: "#e6962b",
            orange3: "#ffae52",
            orange4: "#ffc982",
            red1: "#f44336",
            red2: "#e57373",
            red3: "#ef9a9a",
            red4: "#ffcdd2",
            yellow1: "#ffeb3b",
            yellow2: "#fff176",
            yellow3: "#fff59d",
            yellow4: "#fff9c4",
          },
        },
      },
      fontSize: {
        xs: "12px",
        sm: "14px",
        base: "16px",
        lg: "18px",
        xl: "20px",
        "2xl": "21px",
        "3xl": "24px",
        "4xl": "28px",
        "5xl": "32px",
        "6xl": "36px",
        "7xl": "42px",
      },
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "Noto Sans",
          "Helvetica",
          "Arial",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
        ],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        s: "0.375rem",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
