import { Inter } from "next/font/google";
import "react-circular-progressbar/dist/styles.css";
import "react-toastify/dist/ReactToastify.css";
import "@theme-toggles/react/css/Lightbulb.css";
import "../styles/globals.css";
import { SplashScreenProvider } from "@/context/SplashScreenProvider";
import SplashScreen from "@/components/SplashScreen/SplashScreen";
import { ThemeProvider } from "@/context/ThemeProvider";
import { Navbar, Footer, GreetingPopup } from "@/components";
import { ToastContainer, toast } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <ThemeProvider>
          <SplashScreenProvider>
            <SplashScreen />
            <ToastContainer />
            <GreetingPopup />
            <Navbar />
            {children}
            <Footer />
          </SplashScreenProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
