import { Inter } from "next/font/google";
import "../styles/globals.css";
import { SplashScreenProvider } from "@/context/SplashScreenProvider";
import SplashScreen from "@/components/SplashScreen/SplashScreen";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SplashScreenProvider>
          <SplashScreen />
          {children}
        </SplashScreenProvider>
      </body>
    </html>
  );
}
