/**
 * NOTE: All question sets here (and their Q&A pairs) were generated by AI
 * to help with knowledge retention across a variety of technical topics.
 *
 * This File Contains the questions used in Dev Quiz.
 * It holds arrays of question objects, each representing a specific technical area.
 *
 * Each question object has the following structure:
 * - `id`: A unique identifier for the question.
 * - `topic`: The subject or category of the question (e.g., React, JavaScript, Node.js).
 * - `question`: The text of the question being asked.
 * - `language`: (Optional) A string indicating the programming language for code-related questions.
 * - `code`: (Optional) A boolean indicating if the question involves code.
 * - `options`: An array of possible answers, each with a `text` property and an optional `code` property.
 * - `answer`: The correct answer for the question.
 * - `explanation`: An explanation of why the answer is correct, with optional code examples.
 *
 * Topic covered in this file:
 * - CSS (Styling, layout, responsive design, preprocessors)
 */

export const cssQuestions = [
  // 1–30: STANDARD MULTIPLE-CHOICE (MEDIUM–ADVANCED)

  {
    id: 1,
    topic: "CSS",
    question:
      "Which of the following statements about the CSS box model is true?",
    code: false,
    language: false,
    options: [
      {
        text: "Margin is included in the element's total width when box-sizing is set to border-box",
        code: false,
      },
      {
        text: "Padding is always excluded from the total width, regardless of box-sizing",
        code: false,
      },
      {
        text: "border-box includes padding and border in an element's total width/height",
        code: false,
      },
      {
        text: "content-box includes margin and padding in the total width/height",
        code: false,
      },
    ],
    answer:
      "border-box includes padding and border in an element's total width/height",
    explanation: {
      text: "With box-sizing: border-box, the element's specified width and height include its content area, padding, and border—but not its margin.",
      code: false,
    },
  },
  {
    id: 2,
    topic: "CSS",
    question:
      "Which CSS unit is relative to the font size of the root HTML element?",
    code: false,
    language: false,
    options: [
      { text: "em", code: false },
      { text: "rem", code: false },
      { text: "%", code: false },
      { text: "vw", code: false },
    ],
    answer: "rem",
    explanation: {
      text: "rem units scale relative to the root (html) element’s font size, whereas em units scale relative to the font size of the current element’s parent.",
      code: false,
    },
  },
  {
    id: 3,
    topic: "CSS",
    question:
      "How can you center a block-level element horizontally using modern CSS (assuming no fixed width)?",
    code: false,
    language: false,
    options: [
      { text: "Give the element margin: 0 auto", code: false },
      { text: "Set text-align: center on the element itself", code: false },
      { text: "Apply float: center", code: false },
      {
        text: "Add display: flex and justify-content: center to the element",
        code: false,
      },
    ],
    answer: "Give the element margin: 0 auto",
    explanation: {
      text: "For a block-level element with a fixed width, margin: 0 auto horizontally centers it in its parent container. Alternatively, with flex containers, you'd center via justify-content, but the question references block-level classic approach.",
      code: false,
    },
  },
  {
    id: 4,
    topic: "CSS",
    question:
      "Which of the following pseudo-classes targets an element only if it is currently the target of the URL hash?",
    code: false,
    language: false,
    options: [
      { text: ":target", code: false },
      { text: ":focus-within", code: false },
      { text: ":in-range", code: false },
      { text: ":visited", code: false },
    ],
    answer: ":target",
    explanation: {
      text: ":target selects the element whose id matches the URL’s fragment (hash). For example, #section2 in the URL would target an element with id='section2'.",
      code: false,
    },
  },
  {
    id: 5,
    topic: "CSS",
    question:
      "In CSS Grid, what does the 'auto-fit' keyword do when defining track sizes in repeat()?",
    code: false,
    language: false,
    options: [
      {
        text: "Automatically creates enough rows for the content to fit vertically",
        code: false,
      },
      {
        text: "Fills the container with as many columns/rows of the defined size as possible, possibly creating empty tracks",
        code: false,
      },
      {
        text: "Disables auto-placement of grid items",
        code: false,
      },
      {
        text: "Makes grid items automatically fill leftover space in a container",
        code: false,
      },
    ],
    answer:
      "Fills the container with as many columns/rows of the defined size as possible, possibly creating empty tracks",
    explanation: {
      text: "auto-fit in combination with minmax() can create responsive columns that expand to fill space or collapse if there's not enough space.",
      code: false,
    },
  },
  {
    id: 6,
    topic: "CSS",
    question: "Which of these statements about CSS specificity is correct?",
    code: false,
    language: false,
    options: [
      {
        text: "Inline styles have lower specificity than IDs",
        code: false,
      },
      {
        text: "IDs have higher specificity than classes",
        code: false,
      },
      {
        text: "Type selectors (e.g., h1) have higher specificity than classes",
        code: false,
      },
      {
        text: "Universal selectors (*) override everything",
        code: false,
      },
    ],
    answer: "IDs have higher specificity than classes",
    explanation: {
      text: "The specificity order (lowest to highest) is typically: universal selectors < type selectors < classes < attributes/pseudo-classes < IDs < inline styles < !important. IDs outrank classes.",
      code: false,
    },
  },
  {
    id: 7,
    topic: "CSS",
    question: "What does the 'clearfix' hack typically address?",
    code: false,
    language: false,
    options: [
      {
        text: "Forcing older browsers to treat fonts consistently across OSes",
        code: false,
      },
      {
        text: "Stopping floating child elements from overflowing their parent container",
        code: false,
      },
      {
        text: "Clearing out default paddings and margins of elements",
        code: false,
      },
      {
        text: "Enabling flex layouts in older IE browsers",
        code: false,
      },
    ],
    answer:
      "Stopping floating child elements from overflowing their parent container",
    explanation: {
      text: "The clearfix hack (e.g. .clearfix::after { content: ''; display: block; clear: both; }) helps parent elements to wrap floated children properly.",
      code: false,
    },
  },
  {
    id: 8,
    topic: "CSS",
    question:
      "Which property is used to create a 3D effect by modifying the z-axis position of an element in CSS transforms?",
    code: false,
    language: false,
    options: [
      { text: "transform: perspective()", code: false },
      { text: "transform: rotateZ()", code: false },
      { text: "transform: translateZ()", code: false },
      { text: "transform: matrix3d()", code: false },
    ],
    answer: "transform: translateZ()",
    explanation: {
      text: "translateZ(n) moves the element along the z-axis, potentially giving a 3D effect, especially if there's a perspective set on a parent container.",
      code: false,
    },
  },
  {
    id: 9,
    topic: "CSS",
    question:
      "How can you create a keyframe animation that moves an element from left to right over 2 seconds, repeating infinitely?",
    code: false,
    language: false,
    options: [
      {
        text: "Use transform: scale() from 0 to 1",
        code: false,
      },
      {
        text: "Use transition: left 2s infinite both",
        code: false,
      },
      {
        text: "Define @keyframes, then apply animation: yourAnimation 2s infinite",
        code: false,
      },
      {
        text: "Use the :hover pseudo-class to move the element only on hover",
        code: false,
      },
    ],
    answer:
      "Define @keyframes, then apply animation: yourAnimation 2s infinite",
    explanation: {
      text: "Keyframes with from/to or 0%/100% for transform: translateX() (or left property) combined with animation properties produce a repeating movement.",
      code: false,
    },
  },
  {
    id: 10,
    topic: "CSS",
    question:
      "Which of the following is the correct syntax for a media query targeting screens with a max width of 600px?",
    code: false,
    language: false,
    options: [
      {
        text: "@media (screen) and (max-width: 600px) {}",
        code: false,
      },
      {
        text: "@media screen and (max-width: 600px) {}",
        code: false,
      },
      {
        text: "@media only screen with max-width = 600px {}",
        code: false,
      },
      {
        text: "@media all(max-width=600px) {}",
        code: false,
      },
    ],
    answer: "@media screen and (max-width: 600px) {}",
    explanation: {
      text: "The standard approach is @media screen and (max-width: 600px) { /* rules */ }. The 'only' keyword is optional, and the syntax uses parentheses around (max-width: 600px).",
      code: false,
    },
  },
  {
    id: 11,
    topic: "CSS",
    question:
      "Which property ensures that an element maintains a certain aspect ratio if either width or height changes, commonly used for responsive iframes or videos?",
    code: false,
    language: false,
    options: [
      { text: "aspect-ratio", code: false },
      { text: "ratio-box", code: false },
      { text: "object-fit", code: false },
      { text: "object-position", code: false },
    ],
    answer: "aspect-ratio",
    explanation: {
      text: "The `aspect-ratio` property (e.g., aspect-ratio: 16/9) ensures the box’s height and width maintain that ratio in modern browsers.",
      code: false,
    },
  },
  {
    id: 12,
    topic: "CSS",
    question:
      "Which technique can be used to visually hide text but keep it accessible to screen readers?",
    code: false,
    language: false,
    options: [
      { text: "display: none;", code: false },
      { text: "text-opacity: 0;", code: false },
      { text: "visibility: hidden;", code: false },
      {
        text: "Using a clip/clip-path or absolute positioning off-screen technique",
        code: false,
      },
    ],
    answer:
      "Using a clip/clip-path or absolute positioning off-screen technique",
    explanation: {
      text: "display: none; and visibility: hidden; remove the element from screen readers. A common pattern is `.sr-only { position: absolute; left: -9999px; }` or a clipping method to hide visually but not to AT.",
      code: false,
    },
  },
  {
    id: 13,
    topic: "CSS",
    question:
      "In a Flexbox container, which property controls how remaining space is distributed among flex items?",
    code: false,
    language: false,
    options: [
      { text: "flex: 1 1 auto", code: false },
      { text: "justify-content", code: false },
      { text: "align-items", code: false },
      { text: "flex-grow", code: false },
    ],
    answer: "flex-grow",
    explanation: {
      text: "flex-grow determines how much a flex item will grow relative to the rest of the flex items when there's available space. It's the first value in the shorthand flex property (flex-grow flex-shrink flex-basis).",
      code: false,
    },
  },
  {
    id: 14,
    topic: "CSS",
    question:
      "Which rule prevents a flex item from shrinking below its content size?",
    code: false,
    language: false,
    options: [
      { text: "flex-shrink: 1", code: false },
      { text: "flex-basis: content", code: false },
      { text: "flex-shrink: 0", code: false },
      { text: "align-self: stretch", code: false },
    ],
    answer: "flex-shrink: 0",
    explanation: {
      text: "Setting flex-shrink: 0 tells the item not to shrink when there's not enough space in the flex container.",
      code: false,
    },
  },
  {
    id: 15,
    topic: "CSS",
    question:
      "Which method is typically used to serve different CSS files for older browsers (like IE) without affecting modern browsers?",
    code: false,
    language: false,
    options: [
      {
        text: "Using conditional comments (e.g., <!--[if lte IE 9]> <link ...> <![endif]--> )",
        code: false,
      },
      { text: "Using a partial <doctype> to trick the browser", code: false },
      { text: "All modern browsers ignore CSS anyway", code: false },
      { text: "Use @media legacy in the main stylesheet", code: false },
    ],
    answer:
      "Using conditional comments (e.g., <!--[if lte IE 9]> <link ...> <![endif]--> )",
    explanation: {
      text: "Conditional comments are recognized by old versions of Internet Explorer, letting you serve fallback or polyfill CSS. Modern browsers ignore them.",
      code: false,
    },
  },
  {
    id: 16,
    topic: "CSS",
    question: "Which of the following statements about CSS animations is true?",
    code: false,
    language: false,
    options: [
      {
        text: "Animations always require JavaScript to define keyframes",
        code: false,
      },
      {
        text: "An animation-duration must be set, or the animation won't run",
        code: false,
      },
      {
        text: "CSS animations cannot be repeated automatically",
        code: false,
      },
      {
        text: "transition and animation are the same property used interchangeably",
        code: false,
      },
    ],
    answer: "An animation-duration must be set, or the animation won't run",
    explanation: {
      text: "Without a duration, CSS animations won't play. It's required along with the animation-name or keyframes definition.",
      code: false,
    },
  },
  {
    id: 17,
    topic: "CSS",
    question:
      "What does the 'contain' value do in the background-size property?",
    code: false,
    language: false,
    options: [
      {
        text: "Scales the background image to fill the container, possibly cropping",
        code: false,
      },
      {
        text: "Scales the image to the smallest size such that both width and height fit inside the container",
        code: false,
      },
      { text: "Repeats the image in both directions", code: false },
      { text: "Keeps the image at its original size", code: false },
    ],
    answer:
      "Scales the image to the smallest size such that both width and height fit inside the container",
    explanation: {
      text: "background-size: contain ensures the entire image is visible, fitting either width or height to the container's boundary. 'cover' is the one that may crop.",
      code: false,
    },
  },
  {
    id: 18,
    topic: "CSS",
    question:
      "Which CSS technique helps avoid FOUC (Flash of Unstyled Content) when using web fonts?",
    code: false,
    language: false,
    options: [
      {
        text: "Manually loading fonts via JavaScript, then adding them to the DOM once ready",
        code: false,
      },
      {
        text: "Ensuring the font is loaded over HTTP instead of HTTPS",
        code: false,
      },
      {
        text: "Using the font-display descriptor (e.g., font-display: swap) or a font loading strategy",
        code: false,
      },
      {
        text: "Defining the font last in the CSS file to override everything",
        code: false,
      },
    ],
    answer:
      "Using the font-display descriptor (e.g., font-display: swap) or a font loading strategy",
    explanation: {
      text: "FOUC can be minimized by specifying how the font is displayed while loading (swap, optional, fallback) or by using a JS-based loading approach (e.g., Font Face Observer).",
      code: false,
    },
  },
  {
    id: 19,
    topic: "CSS",
    question:
      "Which of the following is a benefit of using BEM (Block, Element, Modifier) naming methodology?",
    code: false,
    language: false,
    options: [
      { text: "Reduces the length of class names significantly", code: false },
      {
        text: "Makes CSS more predictable and avoids collisions by creating clear naming conventions",
        code: false,
      },
      { text: "Eliminates the need for media queries", code: false },
      { text: "Allows inline JavaScript in CSS rules", code: false },
    ],
    answer:
      "Makes CSS more predictable and avoids collisions by creating clear naming conventions",
    explanation: {
      text: "BEM's naming rules help keep styles modular and avoid collisions, improving maintainability. It usually results in longer class names but better clarity.",
      code: false,
    },
  },
  {
    id: 20,
    topic: "CSS",
    question:
      "Which property specifies how an element's content should be fitted if the content is too big for its container in a flex or grid context?",
    code: false,
    language: false,
    options: [
      { text: "object-fit", code: false },
      { text: "overflow-wrap", code: false },
      { text: "justify-items", code: false },
      { text: "align-content", code: false },
    ],
    answer: "overflow-wrap",
    explanation: {
      text: "overflow-wrap (formerly word-wrap) determines how text will break if it overflows. object-fit is for images/videos in a replaced element context, not text or general content layout.",
      code: false,
    },
  },
  {
    id: 21,
    topic: "CSS",
    question:
      "Which pseudo-element can be used to insert content before an element's content?",
    code: false,
    language: false,
    options: [
      { text: "::before", code: false },
      { text: "::first-line", code: false },
      { text: "::placeholder", code: false },
      { text: "::backdrop", code: false },
    ],
    answer: "::before",
    explanation: {
      text: "::before (or :before in old syntax) inserts content before the element’s main content. ::backdrop is used for fullscreen modals, ::placeholder is for input placeholders, and ::first-line modifies the first line of text only.",
      code: false,
    },
  },
  {
    id: 22,
    topic: "CSS",
    question:
      "In CSS transitions, what does the 'transition-timing-function' property define?",
    code: false,
    language: false,
    options: [
      { text: "The total duration of the transition", code: false },
      {
        text: "How property values change speed over the transition's duration (e.g., ease-in)",
        code: false,
      },
      { text: "The number of times the transition repeats", code: false },
      {
        text: "Whether the transition also changes background images",
        code: false,
      },
    ],
    answer:
      "How property values change speed over the transition's duration (e.g., ease-in)",
    explanation: {
      text: "transition-timing-function (ease, linear, ease-in-out, etc.) controls the acceleration curve of the transition between start and end states.",
      code: false,
    },
  },
  {
    id: 23,
    topic: "CSS",
    question:
      "Which property can help prevent child elements from 'floating' outside a container that does not have a defined height?",
    code: false,
    language: false,
    options: [
      { text: "overflow: auto;", code: false },
      { text: "height: 100%;", code: false },
      { text: "position: relative;", code: false },
      { text: "float: none;", code: false },
    ],
    answer: "overflow: auto;",
    explanation: {
      text: "Setting overflow: auto (or hidden) on a parent can force it to expand around floated children. Alternatively, the clearfix hack or display: flow-root can be used.",
      code: false,
    },
  },
  {
    id: 24,
    topic: "CSS",
    question:
      "Which of the following is true about the layering of positioned elements via z-index?",
    code: false,
    language: false,
    options: [
      {
        text: "z-index works on statically positioned elements by default",
        code: false,
      },
      {
        text: "A higher z-index always places an element on top, regardless of stacking contexts",
        code: false,
      },
      {
        text: "Only positioned elements (relative, absolute, fixed) can have a z-index effect",
        code: false,
      },
      {
        text: "A z-index of -1 is invalid in modern browsers",
        code: false,
      },
    ],
    answer:
      "Only positioned elements (relative, absolute, fixed) can have a z-index effect",
    explanation: {
      text: "z-index only applies to elements that have a position set to something other than static (relative, absolute, fixed, sticky). Also, each stacking context is important to consider.",
      code: false,
    },
  },
  {
    id: 25,
    topic: "CSS",
    question:
      "Which at-rule in CSS allows you to define custom variables (properties) that can be reused throughout a stylesheet?",
    code: false,
    language: false,
    options: [
      { text: "@custom-variables", code: false },
      { text: "@var", code: false },
      { text: ":root {}", code: false },
      {
        text: "Trick question: custom properties are declared directly in a selector, not an at-rule",
        code: false,
      },
    ],
    answer:
      "Trick question: custom properties are declared directly in a selector, not an at-rule",
    explanation: {
      text: "CSS custom properties (variables) are declared using `--propertyName` inside a selector, often `:root { --mainColor: #333; }`. There's no dedicated @var or @custom-variables at-rule for them in CSS.",
      code: false,
    },
  },
  {
    id: 26,
    topic: "CSS",
    question:
      "Which preprocessors provide features like mixins, nesting, and variables, compiling down to valid CSS?",
    code: false,
    language: false,
    options: [
      { text: "LESS, Sass/SCSS, Stylus", code: false },
      { text: "TypeScript, Flow, Babel", code: false },
      { text: "EJS, Handlebars, Mustache", code: false },
      { text: "Jest, Mocha, Cypress", code: false },
    ],
    answer: "LESS, Sass/SCSS, Stylus",
    explanation: {
      text: "LESS, SASS/SCSS, and Stylus are common CSS preprocessors that add advanced features, compiled to plain CSS for browsers.",
      code: false,
    },
  },
  {
    id: 27,
    topic: "CSS",
    question:
      "Which property can help maintain consistent spacing between flex items, replacing the need for margins on child elements?",
    code: false,
    language: false,
    options: [
      { text: "column-gap / row-gap (or gap)", code: false },
      { text: "margin-inline", code: false },
      { text: "outline-spacing", code: false },
      { text: "flex-spacing", code: false },
    ],
    answer: "column-gap / row-gap (or gap)",
    explanation: {
      text: "In modern browsers, 'gap' works in flex containers similarly to how grid-gap works in CSS Grid, simplifying consistent spacing between items.",
      code: false,
    },
  },
  {
    id: 28,
    topic: "CSS",
    question:
      "Which value of 'display' creates a new block-level formatting context for the element, ignoring floats from sibling elements?",
    code: false,
    language: false,
    options: [
      { text: "display: table", code: false },
      { text: "display: block", code: false },
      { text: "display: flow-root", code: false },
      { text: "display: flex", code: false },
    ],
    answer: "display: flow-root",
    explanation: {
      text: "flow-root sets an element to become a new block formatting context (like a 'clearfix' effect), preventing floats from overlapping outside of it.",
      code: false,
    },
  },
  {
    id: 29,
    topic: "CSS",
    question:
      "Which of the following statements about layering multiple background images is correct?",
    code: false,
    language: false,
    options: [
      {
        text: "You cannot layer multiple backgrounds; only one background image is allowed by CSS",
        code: false,
      },
      {
        text: "Multiple images can be specified in the background-image property, separated by commas",
        code: false,
      },
      {
        text: "You have to use z-index to stack multiple background images",
        code: false,
      },
      {
        text: "background: top, middle, bottom are used to define separate layers",
        code: false,
      },
    ],
    answer:
      "Multiple images can be specified in the background-image property, separated by commas",
    explanation: {
      text: "For example: `background-image: url('img1.png'), url('img2.png');` You can also define multiple background-size, background-position, etc., for each layer separated by commas in the same order.",
      code: false,
    },
  },
  {
    id: 30,
    topic: "CSS",
    question:
      "Which of the following is a recommended approach to improving CSS performance?",
    code: false,
    language: false,
    options: [
      {
        text: "Use many universal selectors (*) to style multiple elements quickly",
        code: false,
      },
      {
        text: "Rely heavily on descendant selectors (e.g., .nav ul li a) for clarity",
        code: false,
      },
      {
        text: "Use more specific selectors with IDs to override everything easily",
        code: false,
      },
      {
        text: "Keep selectors shallow (avoid deeply nested descendants) and reduce unnecessary complexity",
        code: false,
      },
    ],
    answer:
      "Keep selectors shallow (avoid deeply nested descendants) and reduce unnecessary complexity",
    explanation: {
      text: "Deeply nested or highly specific selectors can impact performance and maintainability. Minimizing complexity (e.g. short class-based selectors) is generally recommended.",
      code: false,
    },
  },

  // 31–40: CODE COMPLETION / SPOT THE ERROR

  // 31
  {
    id: 31,
    topic: "CSS",
    question:
      "Spot the error: Why doesn't this snippet center the text horizontally?\n\nbody {\n  text-align: center;\n}\n.container {\n  width: 80%;\n  margin: auto;\n  text-align: left;\n}\n",
    code: `body {
  text-align: center;
}
.container {
  width: 80%;
  margin: auto;
  text-align: left;
}`,
    language: "css",
    options: [
      {
        text: "text-align is overridden by .container { text-align: left }",
        code: false,
      },
      {
        text: "margin: auto has no effect on .container",
        code: false,
      },
      {
        text: "You need an inline element for text-align: center to work",
        code: false,
      },
      {
        text: "text-align: center must be placed in .container not the body",
        code: false,
      },
    ],
    answer: "text-align is overridden by .container { text-align: left }",
    explanation: {
      text: "The .container rule sets text-align: left, overriding the body rule, so text won't be centered within .container.",
      code: false,
    },
  },

  // 32
  {
    id: 32,
    topic: "CSS",
    question:
      "Complete the code: If you want a transition on hover from red to blue background over 0.5 seconds, which code snippet is correct?\n\n.button {\n  background-color: red;\n  transition: __________;\n}\n.button:hover {\n  background-color: blue;\n}",
    code: ` .button {
  background-color: red;
  transition: /* ? */;
}
.button:hover {
  background-color: blue;
}`,
    language: "css",
    options: [
      {
        text: "transition: background-color 0.5s;",
        code: false,
      },
      {
        text: "transition: 0.5s;",
        code: false,
      },
      {
        text: "transition-duration: color 0.5s;",
        code: false,
      },
      {
        text: "transition-property: background; transition-duration: 0.5ms;",
        code: false,
      },
    ],
    answer: "transition: background-color 0.5s;",
    explanation: {
      text: "You need to specify which property is transitioning and the duration. The correct property is background-color, and 0.5s is the time.",
      code: false,
    },
  },

  // 33
  {
    id: 33,
    topic: "CSS",
    question:
      "Spot the issue: This code tries to create a 2-column grid, but only one column appears.\n\n.container {\n  display: grid;\n  grid-template-columns: 200px,\n  gap: 20px;\n}",
    code: ` .container {
  display: grid;
  grid-template-columns: 200px,
  gap: 20px;
}`,
    language: "css",
    options: [
      {
        text: "There's a missing second column size in grid-template-columns; it needs at least 2 sizes separated by space or comma",
        code: false,
      },
      {
        text: "gap: 20px is unsupported in modern browsers",
        code: false,
      },
      {
        text: "The display property should be display: inline-grid",
        code: false,
      },
      {
        text: "We must specify grid-template-rows also",
        code: false,
      },
    ],
    answer:
      "There's a missing second column size in grid-template-columns; it needs at least 2 sizes separated by space or comma",
    explanation: {
      text: "To create two columns, you might do grid-template-columns: 200px 1fr; or 200px auto; etc. Here, only one size is defined, so only one column is created.",
      code: false,
    },
  },

  // 34
  {
    id: 34,
    topic: "CSS",
    question:
      "Complete the code to absolutely position an element 50px from the top and 20px from the left, with a width of 200px.\n\n.box {\n  position: absolute;\n  ________: 50px;\n  ________: 20px;\n  ________: 200px;\n}",
    code: `.box {
  position: absolute;
  /* ? */
}`,
    language: "css",
    options: [
      {
        text: "top: 50px; left: 20px; width: 200px;",
        code: false,
      },
      {
        text: "margin-top: 50px; padding-left: 20px; width: 200px;",
        code: false,
      },
      {
        text: "transform: translate(50px, 20px); min-width: 200px;",
        code: false,
      },
      {
        text: "position: relative; top: 50px; width: 200px;",
        code: false,
      },
    ],
    answer: "top: 50px; left: 20px; width: 200px;",
    explanation: {
      text: "For an absolutely positioned element, top/left define the offset from the containing block, and width sets its width. margin-top or transform do not correspond to top/left offsets in absolute positioning.",
      code: false,
    },
  },

  // 35
  {
    id: 35,
    topic: "CSS",
    question:
      "Identify the problem in this SCSS snippet:\n\n$primary: #ff0000\n.btn {\n  color: $primary;\n}\n\nIt doesn't compile. Why?",
    code: `$primary: #ff0000
.btn {
  color: $primary;
}`,
    language: "css",
    options: [
      {
        text: "Sass variables must be declared with var(--primary) syntax",
        code: false,
      },
      {
        text: "There's a missing semicolon after the $primary declaration in SCSS",
        code: false,
      },
      {
        text: "SCSS doesn't allow color variables without an @mixin",
        code: false,
      },
      {
        text: "You must import sass-colors to use color variables",
        code: false,
      },
    ],
    answer:
      "There's a missing semicolon after the $primary declaration in SCSS",
    explanation: {
      text: "In SCSS syntax, each variable assignment must end with a semicolon: `$primary: #ff0000;` Omitting it causes a parse error.",
      code: false,
    },
  },

  // 36
  {
    id: 36,
    topic: "CSS",
    question:
      "Fill in the correct code to create a dashed border of 2px around .box using border shorthand:\n\n.box {\n  ________\n}",
    code: `.box {
  /* ? */
}`,
    language: "css",
    options: [
      {
        text: "border: dashed 2px;",
        code: false,
      },
      {
        text: "border: 2px #000 dashed;",
        code: false,
      },
      {
        text: "border: 2px dashed #000;",
        code: false,
      },
      {
        text: "border: #000 dashed 2px black;",
        code: false,
      },
    ],
    answer: "border: 2px dashed #000;",
    explanation: {
      text: "The typical border shorthand order is width, style, color. e.g. `border: 2px dashed #000;`",
      code: false,
    },
  },

  // 37
  {
    id: 37,
    topic: "CSS",
    question:
      "Spot the issue: The developer wants all paragraphs in .content to be bold, but nothing changes:\n\n.content p {\n  font-weight: bold;\n}\np {\n  font-weight: normal;\n}",
    code: `.content p {
  font-weight: bold;
}
p {
  font-weight: normal;
}`,
    language: "css",
    options: [
      {
        text: "The second p selector has the same specificity, so it overrides .content p if it's declared after it",
        code: false,
      },
      {
        text: ".content p has a higher specificity, so it should override p",
        code: false,
      },
      {
        text: "font-weight doesn't work with paragraphs by default",
        code: false,
      },
      {
        text: "You need !important to override the normal weight",
        code: false,
      },
    ],
    answer:
      "The second p selector has the same specificity, so it overrides .content p if it's declared after it",
    explanation: {
      text: "A type selector (p) and a class plus type selector (.content p) have the same specificity level in terms of classes/elements (not counting universal). Actually, .content p is more specific. But if the p {} rule is placed last, it can override it due to the cascade. One could reorder or increase specificity with .content p { } after p {} or more specific rule.",
      code: false,
    },
  },

  // 38
  {
    id: 38,
    topic: "CSS",
    question:
      "Complete the snippet to create a linear gradient background from red at the top to blue at the bottom:\n\n.box {\n  background: ________;\n}",
    code: `.box {
  background: /* ? */;
}`,
    language: "css",
    options: [
      {
        text: "linear-gradient(to bottom, red, blue)",
        code: false,
      },
      {
        text: "gradient(linear, top, color(red), color(blue))",
        code: false,
      },
      {
        text: "radial-gradient(red, blue)",
        code: false,
      },
      {
        text: "linear-gradient(to right, red, blue)",
        code: false,
      },
    ],
    answer: "linear-gradient(to bottom, red, blue)",
    explanation: {
      text: "A linear-gradient with 'to bottom' means top is red, bottom is blue. Another valid approach is linear-gradient(red, blue) which defaults top to bottom, but 'to bottom' is clearer.",
      code: false,
    },
  },

  // 39
  {
    id: 39,
    topic: "CSS",
    question:
      "Spot the error: The developer is trying to apply a box-shadow, but nothing appears:\n\n.shadow {\n  box-shadow: 0 2px 5px 0;\n}",
    code: `.shadow {
  box-shadow: 0 2px 5px 0;
}`,
    language: "css",
    options: [
      {
        text: "box-shadow requires the color parameter (e.g., rgba(0,0,0,0.3))",
        code: false,
      },
      {
        text: "You must add !important to box-shadow",
        code: false,
      },
      {
        text: "Positioning must be relative for box-shadow to appear",
        code: false,
      },
      {
        text: "The box-shadow property is only for text shadows, not box shadows",
        code: false,
      },
    ],
    answer: "box-shadow requires the color parameter (e.g., rgba(0,0,0,0.3))",
    explanation: {
      text: "box-shadow syntax includes offsets, blur, spread, and color. At least a color is needed to see the shadow. Example: `box-shadow: 0 2px 5px 0 rgba(0,0,0,0.3);`",
      code: false,
    },
  },

  // 40
  {
    id: 40,
    topic: "CSS",
    question:
      'Complete the snippet to import a Google font in CSS:\n\n@import url("________");',
    code: `@import url("/* ? */");`,
    language: "css",
    options: [
      {
        text: "https://fonts.google.com/someFont.css",
        code: false,
      },
      {
        text: "https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap",
        code: false,
      },
      {
        text: "https://fonts.googleapis.com/ImportFonts?OpenSans",
        code: false,
      },
      {
        text: "You cannot import fonts via @import in CSS",
        code: false,
      },
    ],
    answer:
      "https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap",
    explanation: {
      text: "Google Fonts typically uses an @import link from the fonts.googleapis.com domain with the desired font family, weights, and display param. Example: `@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap');`",
      code: false,
    },
  },
];
