/**
 * NOTE: All question sets here (and their Q&A pairs) were generated by AI
 * to help with knowledge retention across a variety of technical topics.
 *
 * This File Contains the questions used in Dev Quiz.
 * It holds arrays of question objects, each representing a specific technical area.
 *
 * Each question object has the following structure:
 * - `id`: A unique identifier for the question.
 * - `topic`: The subject or category of the question (e.g., React, JavaScript, Node.js).
 * - `question`: The text of the question being asked.
 * - `language`: (Optional) A string indicating the programming language for code-related questions.
 * - `code`: (Optional) A boolean indicating if the question involves code.
 * - `options`: An array of possible answers, each with a `text` property and an optional `code` property.
 * - `answer`: The correct answer for the question.
 * - `explanation`: An explanation of why the answer is correct, with optional code examples.
 *
 * Topic covered in this file:
 * - HTML (Semantic elements, forms, HTML5 APIs)
 */

export const htmlQuestions = [
  {
    id: 1,
    topic: "HTML",
    question:
      "Which semantic HTML5 element is best suited for wrapping content that is only tangentially related to the main content?",
    code: false,
    language: false,
    options: [
      { text: "<aside>", code: false },
      { text: "<section>", code: false },
      { text: "<main>", code: false },
      { text: "<article>", code: false },
    ],
    answer: "<aside>",
    explanation: {
      text: "`<aside>` is meant for content related to or supporting the surrounding content (e.g., sidebars, pull quotes). It's distinct from `<section>` (generic thematic grouping), `<article>` (self-contained piece), and `<main>` (principal content).",
      code: false,
    },
  },
  {
    id: 2,
    topic: "HTML",
    question:
      "Which HTML5 element is used to represent a scalar measurement within a known range, such as a disk usage indicator?",
    code: false,
    language: false,
    options: [
      { text: "<meter>", code: false },
      { text: "<progress>", code: false },
      { text: "<range>", code: false },
      { text: "<gauge>", code: false },
    ],
    answer: "<meter>",
    explanation: {
      text: "`<meter>` indicates a measurable value or a fractional value within a known range (e.g., disk usage 70% of 100GB). `<progress>` is used for an ongoing process (e.g., a download in progress).",
      code: false,
    },
  },
  {
    id: 3,
    topic: "HTML",
    question:
      "Which HTML attribute is used to provide a machine-readable translation of a human-readable content, often used in microdata or SEO contexts?",
    code: false,
    language: false,
    options: [
      { text: "itemprop", code: false },
      { text: "data-attr", code: false },
      { text: "machine-lang", code: false },
      { text: "aria-label", code: false },
    ],
    answer: "itemprop",
    explanation: {
      text: "`itemprop` is used as part of microdata to specify the property of an item. `aria-label` deals with accessibility, and `data-attr` is a custom data attribute (not specifically for SEO).",
      code: false,
    },
  },
  {
    id: 4,
    topic: "HTML",
    question:
      "In HTML5 forms, which attribute prevents the browser from validating form inputs upon submission?",
    code: false,
    language: false,
    options: [
      { text: "disabled", code: false },
      { text: "inert", code: false },
      { text: "novalidate", code: false },
      { text: "ignore-validation", code: false },
    ],
    answer: "novalidate",
    explanation: {
      text: "`novalidate` on a form element tells the browser to skip built-in validation checks (like `required`, `type` checks, etc.).",
      code: false,
    },
  },
  {
    id: 5,
    topic: "HTML",
    question:
      "When dealing with responsive images, which attribute specifies a list of possible image sources along with their pixel density or width descriptors?",
    code: false,
    language: false,
    options: [
      { text: "src", code: false },
      { text: "sizes", code: false },
      { text: "srcset", code: false },
      { text: "picture", code: false },
    ],
    answer: "srcset",
    explanation: {
      text: "`srcset` contains a set of image candidates (with density or width descriptors), while `sizes` defines the layout space. `<picture>` is an element, not an attribute.",
      code: false,
    },
  },
  {
    id: 6,
    topic: "HTML",
    question:
      "Which HTML5 attribute can be used on `<iframe>` to enhance security by restricting features like running scripts or forms inside the iframe?",
    code: false,
    language: false,
    options: [
      { text: "sandbox", code: false },
      { text: "noscroll", code: false },
      { text: "secure-iframe", code: false },
      { text: "disabler", code: false },
    ],
    answer: "sandbox",
    explanation: {
      text: "`sandbox` allows you to enforce stricter security policies on iframes, disabling or limiting certain actions unless specifically allowed.",
      code: false,
    },
  },
  {
    id: 7,
    topic: "HTML",
    question:
      "Which meta tag is critical for controlling the viewport on mobile devices, allowing for responsive design in HTML5?",
    code: false,
    language: false,
    options: [
      { text: "<meta name='mobile' content='true'>", code: false },
      {
        text: "<meta name='device' content='width=device-width'>",
        code: false,
      },
      {
        text: "<meta name='viewport' content='width=device-width, initial-scale=1.0'>",
        code: false,
      },
      { text: "<meta name='scalable' content='no'>", code: false },
    ],
    answer:
      "<meta name='viewport' content='width=device-width, initial-scale=1.0'>",
    explanation: {
      text: "The `viewport` meta tag configures how a page should be displayed on mobile devices. Setting `width=device-width` and `initial-scale=1.0` helps achieve responsive layouts.",
      code: false,
    },
  },
  {
    id: 8,
    topic: "HTML",
    question:
      "What is the main purpose of the 'rel=\"preload\"' link attribute in HTML?",
    code: false,
    language: false,
    options: [
      {
        text: "To load a resource only if the user requests it explicitly",
        code: false,
      },
      {
        text: "To declare a resource that should be prefetched for a future navigation",
        code: false,
      },
      {
        text: "To fetch a resource as soon as possible to improve performance of current navigation",
        code: false,
      },
      {
        text: "To lazy-load images when they come into the viewport",
        code: false,
      },
    ],
    answer:
      "To fetch a resource as soon as possible to improve performance of current navigation",
    explanation: {
      text: 'rel="preload" signals to the browser to download the resource early, improving performance for critical assets (e.g., fonts, key scripts).',
      code: false,
    },
  },
  {
    id: 9,
    topic: "HTML",
    question:
      "Which HTML5 element would you use to group interactive controls and labels within a web form for better structure or accessibility?",
    code: false,
    language: false,
    options: [
      { text: "<fieldset>", code: false },
      { text: "<section>", code: false },
      { text: "<div>", code: false },
      { text: "<group>", code: false },
    ],
    answer: "<fieldset>",
    explanation: {
      text: "A `<fieldset>` groups related controls and labels. Often used with `<legend>` for better accessibility and clarity.",
      code: false,
    },
  },
  {
    id: 10,
    topic: "HTML",
    question:
      "Which attribute on a `<form>` can be used to associate submit buttons with a form located elsewhere in the DOM?",
    code: false,
    language: false,
    options: [
      { text: "target", code: false },
      { text: "form-data", code: false },
      { text: "data-form-id", code: false },
      { text: "form", code: false },
    ],
    answer: "form",
    explanation: {
      text: 'An input or button with `form="someFormId"` can submit a form that is not its direct ancestor, allowing more flexible layouts.',
      code: false,
    },
  },
  {
    id: 11,
    topic: "HTML",
    question:
      "What is the main difference between the `<section>` and `<article>` elements in HTML5?",
    code: false,
    language: false,
    options: [
      {
        text: "`<article>` cannot contain headings, `<section>` can",
        code: false,
      },
      {
        text: "`<article>` is used for stand-alone, self-contained content; `<section>` is for thematically grouped content",
        code: false,
      },
      {
        text: "They are fully interchangeable in modern browsers",
        code: false,
      },
      {
        text: "They are obsolete elements replaced by `<div role='article'>` and `<div role='section'>`",
        code: false,
      },
    ],
    answer:
      "`<article>` is used for stand-alone, self-contained content; `<section>` is for thematically grouped content",
    explanation: {
      text: "An `<article>` is a self-contained composition (e.g., blog post, magazine article). A `<section>` groups related thematic content (e.g., chapters, sections of a doc).",
      code: false,
    },
  },
  {
    id: 12,
    topic: "HTML",
    question:
      "Which HTML attribute can be used to mark input fields for autocompletion by the browser with domain-specific suggestions?",
    code: false,
    language: false,
    options: [
      { text: "autosuggest", code: false },
      { text: "autocomplete", code: false },
      { text: "autofill", code: false },
      { text: "autohint", code: false },
    ],
    answer: "autocomplete",
    explanation: {
      text: "`autocomplete` can be set to on/off, or to specific tokens like 'name', 'email', etc., so the browser can prefill data from user profiles.",
      code: false,
    },
  },
  {
    id: 13,
    topic: "HTML",
    question: "What is the primary purpose of the <template> element in HTML5?",
    code: false,
    language: false,
    options: [
      {
        text: "To store HTML that won't be rendered until cloned via JavaScript",
        code: false,
      },
      { text: "To define the base style for the entire document", code: false },
      { text: "To house inline SVG assets", code: false },
      {
        text: "To provide a fallback for older browsers that don't support HTML5",
        code: false,
      },
    ],
    answer: "To store HTML that won't be rendered until cloned via JavaScript",
    explanation: {
      text: "`<template>` holds markup that is inert by default. JavaScript can clone and insert it into the DOM when needed. Useful in advanced templating or component patterns.",
      code: false,
    },
  },
  {
    id: 14,
    topic: "HTML",
    question:
      "Which of the following statements about the HTML5 drag-and-drop API is true?",
    code: false,
    language: false,
    options: [
      { text: "It only works on `<img>` elements", code: false },
      { text: "It relies on the contenteditable attribute", code: false },
      {
        text: "It uses draggable attributes and events like ondragstart, ondragover, ondrop",
        code: false,
      },
      {
        text: "It is officially deprecated and replaced by Web Components",
        code: false,
      },
    ],
    answer:
      "It uses draggable attributes and events like ondragstart, ondragover, ondrop",
    explanation: {
      text: "HTML5 introduced a set of events and attributes for drag-and-drop, including `draggable='true'`, `ondragstart`, `ondragover`, and `ondrop`. This can be used on many elements, not just images.",
      code: false,
    },
  },
  {
    id: 15,
    topic: "HTML",
    question:
      "Which attribute can be used on input fields to match a specific regex pattern directly in HTML5, without using JavaScript?",
    code: false,
    language: false,
    options: [
      { text: "pattern", code: false },
      { text: "regex", code: false },
      { text: "validate", code: false },
      { text: "match", code: false },
    ],
    answer: "pattern",
    explanation: {
      text: "The `pattern` attribute on input fields allows specifying a regular expression that the input value must match before form submission is considered valid.",
      code: false,
    },
  },
  {
    id: 16,
    topic: "HTML",
    question:
      "Which HTML element is used to provide alternative sources for a `<video>` or `<audio>` element?",
    code: false,
    language: false,
    options: [
      { text: "<media>", code: false },
      { text: "<track>", code: false },
      { text: "<source>", code: false },
      { text: "<alt>", code: false },
    ],
    answer: "<source>",
    explanation: {
      text: "The `<source>` element within `<video>` or `<audio>` allows specifying multiple media sources (formats, resolutions). `<track>` is for captions/subtitles.",
      code: false,
    },
  },
  {
    id: 17,
    topic: "HTML",
    question: "Which doctype is used for modern HTML5 documents?",
    code: false,
    language: false,
    options: [
      { text: "<!DOCTYPE HTML5>", code: false },
      { text: "<!DOCTYPE html>", code: false },
      {
        text: "<!DOCTYPE HTML PUBLIC '-//W3C//DTD HTML 5.0//EN'>",
        code: false,
      },
      { text: "<!DOCTYPE HTML SYSTEM 'about:legacy-compat'>", code: false },
    ],
    answer: "<!DOCTYPE html>",
    explanation: {
      text: "HTML5 uses a simplified doctype: `<!DOCTYPE html>`. It's case-insensitive but typically written in lowercase.",
      code: false,
    },
  },
  {
    id: 18,
    topic: "HTML",
    question:
      "Which element helps define custom, private attributes (metadata) on HTML elements for use by scripts or styling?",
    code: false,
    language: false,
    options: [
      { text: "data-*", code: false },
      { text: "private-attr", code: false },
      { text: "user-field", code: false },
      { text: "meta-attr", code: false },
    ],
    answer: "data-*",
    explanation: {
      text: "`data-*` attributes allow embedding custom data in HTML elements, accessible via JavaScript (e.g. `dataset`) without conflicting with valid attributes.",
      code: false,
    },
  },
  {
    id: 19,
    topic: "HTML",
    question:
      "What is the purpose of the 'http-equiv' attribute in a <meta> tag?",
    code: false,
    language: false,
    options: [
      {
        text: "It sets the default language for the HTML document",
        code: false,
      },
      {
        text: "It provides compatibility or instructions to the browser, e.g., refresh, content-type",
        code: false,
      },
      {
        text: "It defines the character encoding used by JavaScript only",
        code: false,
      },
      {
        text: "It applies only to debugging tools in modern browsers",
        code: false,
      },
    ],
    answer:
      "It provides compatibility or instructions to the browser, e.g., refresh, content-type",
    explanation: {
      text: "`<meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>` was common in older HTML. Also used for refresh, X-UA-Compatible, etc. Now most prefer `<meta charset='utf-8'>` syntax instead.",
      code: false,
    },
  },
  {
    id: 20,
    topic: "HTML",
    question:
      "Which attribute can instruct browsers not to provide suggestions for form fields, improving security for sensitive data entries?",
    code: false,
    language: false,
    options: [
      { text: "autocomplete='off'", code: false },
      { text: "novalidate='true'", code: false },
      { text: "secure='true'", code: false },
      { text: "hidden='true'", code: false },
    ],
    answer: "autocomplete='off'",
    explanation: {
      text: "Setting `autocomplete='off'` can disable browser autofill or suggestions. Often used on password or OTP fields to enhance security or user experience.",
      code: false,
    },
  },
  {
    id: 21,
    topic: "HTML",
    question:
      "How does the `<picture>` element differ from using `<img>` alone?",
    code: false,
    language: false,
    options: [
      {
        text: "<picture> is just another name for <img>, introduced in HTML4",
        code: false,
      },
      {
        text: "The <picture> element allows specifying multiple <source> elements for different viewport sizes or formats",
        code: false,
      },
      {
        text: "<img> is deprecated in favor of <picture>",
        code: false,
      },
      {
        text: "<picture> can be used only for SVG images",
        code: false,
      },
    ],
    answer:
      "The <picture> element allows specifying multiple <source> elements for different viewport sizes or formats",
    explanation: {
      text: "`<picture>` with `<source>` elements provides advanced responsive image capabilities (e.g., WebP for modern browsers, fallback to JPEG).",
      code: false,
    },
  },
  {
    id: 22,
    topic: "HTML",
    question:
      "Which attribute can help ensure that the browser does not load resources it deems non-critical right away, potentially improving page load times?",
    code: false,
    language: false,
    options: [
      { text: "lazy-load", code: false },
      { text: "async", code: false },
      { text: "defer", code: false },
      { text: "loading='lazy'", code: false },
    ],
    answer: "loading='lazy'",
    explanation: {
      text: "For images and iframes, `loading='lazy'` defers loading until they're close to the viewport. This is distinct from `async`/`defer` used on scripts.",
      code: false,
    },
  },
  {
    id: 23,
    topic: "HTML",
    question:
      "Which statement about the 'lang' attribute in the <html> tag is correct?",
    code: false,
    language: false,
    options: [
      {
        text: "It is only used by the browser to pick the correct dictionary for spell-check",
        code: false,
      },
      {
        text: "It helps screen readers and other assistive technologies interpret the language of the document",
        code: false,
      },
      {
        text: "It can be replaced by a meta tag in HTML5",
        code: false,
      },
      {
        text: "It is used to define time zones for date formatting",
        code: false,
      },
    ],
    answer:
      "It helps screen readers and other assistive technologies interpret the language of the document",
    explanation: {
      text: "The `lang` attribute is important for accessibility and search engines, ensuring correct language settings for screen readers and other tools.",
      code: false,
    },
  },
  {
    id: 24,
    topic: "HTML",
    question:
      "Which feature does the 'download' attribute provide when used in an <a> tag?",
    code: false,
    language: false,
    options: [
      { text: "Streams a video directly in the browser", code: false },
      {
        text: "Hints that the target resource should be downloaded as a file rather than opened",
        code: false,
      },
      { text: "Displays the resource in an iframe", code: false },
      { text: "Embeds the resource as text on the page", code: false },
    ],
    answer:
      "Hints that the target resource should be downloaded as a file rather than opened",
    explanation: {
      text: "Using `download` on an anchor prompts browsers to download the linked resource rather than navigating to or rendering it.",
      code: false,
    },
  },
  {
    id: 25,
    topic: "HTML",
    question:
      "Which HTML element is used to define an interactive widget or custom component with encapsulated styling and behavior (part of Web Components)?",
    code: false,
    language: false,
    options: [
      { text: "<shadow>", code: false },
      { text: "<template>", code: false },
      { text: "<slot>", code: false },
      {
        text: "No single element; you typically define a custom element with customElement.define()",
        code: false,
      },
    ],
    answer:
      "No single element; you typically define a custom element with customElement.define()",
    explanation: {
      text: "Web Components rely on custom elements (e.g. `<my-component>`) plus features like Shadow DOM (`attachShadow`) and `<slot>` for content distribution. There's no single `<shadow>` element for the entire approach.",
      code: false,
    },
  },
  {
    id: 26,
    topic: "HTML",
    question:
      "Which statement about 'role' attributes in HTML (ARIA roles) is correct?",
    code: false,
    language: false,
    options: [
      {
        text: "They are only recognized by CSS for styling purposes",
        code: false,
      },
      {
        text: "They override native semantics of an element for assistive technologies",
        code: false,
      },
      {
        text: "They are required for all HTML5 elements",
        code: false,
      },
      {
        text: "They are used to specify how the element should be validated in forms",
        code: false,
      },
    ],
    answer:
      "They override native semantics of an element for assistive technologies",
    explanation: {
      text: "ARIA `role` attributes can change or define the semantic meaning for screen readers or other AT, especially if an element’s semantics are misaligned with its usage.",
      code: false,
    },
  },
  {
    id: 27,
    topic: "HTML",
    question:
      "Which attribute of the <script> tag ensures the script executes only after the HTML has been parsed, but still in the order they appear in the document?",
    code: false,
    language: false,
    options: [
      { text: "async", code: false },
      { text: "defer", code: false },
      { text: "type='module'", code: false },
      { text: "script-lazy", code: false },
    ],
    answer: "defer",
    explanation: {
      text: "A `defer` attribute loads the script in the background and executes it after the document is fully parsed, maintaining the script load order. `async` does not guarantee order.",
      code: false,
    },
  },
  {
    id: 28,
    topic: "HTML",
    question:
      "Which HTML element or attribute is used to group related autocomplete options for <input> elements, offering suggestions as users type?",
    code: false,
    language: false,
    options: [
      { text: "datalist", code: false },
      { text: "autosuggest", code: false },
      { text: "optionset", code: false },
      { text: "fieldset", code: false },
    ],
    answer: "datalist",
    explanation: {
      text: "The `<datalist>` element holds `<option>` elements that provide suggestions for an `<input list='...'>`. This is separate from select boxes or fieldset usage.",
      code: false,
    },
  },
  {
    id: 29,
    topic: "HTML",
    question:
      "What is a recommended practice for including a fallback font in case a custom web font fails to load?",
    code: false,
    language: false,
    options: [
      { text: "Use <nofont> tags", code: false },
      {
        text: "Add multiple font-family values in a CSS rule, e.g. 'FontA', 'Arial', sans-serif",
        code: false,
      },
      {
        text: "There is no fallback mechanism in HTML/CSS for custom fonts",
        code: false,
      },
      {
        text: "Use an iframe that loads a default font if the custom one fails",
        code: false,
      },
    ],
    answer:
      "Add multiple font-family values in a CSS rule, e.g. 'FontA', 'Arial', sans-serif",
    explanation: {
      text: "Specifying a fallback chain in `font-family` ensures that if the primary font fails, a secondary or system default is used. This is a best practice for robust typography.",
      code: false,
    },
  },
  {
    id: 30,
    topic: "HTML",
    question:
      "Which meta element attribute helps manage Content Security Policy (CSP) to mitigate XSS attacks?",
    code: false,
    language: false,
    options: [
      { text: "http-equiv='X-XSS-Protection'", code: false },
      { text: "http-equiv='Content-Security-Policy'", code: false },
      { text: "content='no-referrer'", code: false },
      { text: "name='xss-protect'", code: false },
    ],
    answer: "http-equiv='Content-Security-Policy'",
    explanation: {
      text: "You can set CSP using a meta tag like `<meta http-equiv='Content-Security-Policy' content=\"default-src 'self';\">`, though setting CSP in HTTP headers is often recommended for stronger security.",
      code: false,
    },
  },
];
