/**
 * NOTE: All question sets here (and their Q&A pairs) were generated by AI
 * to help with knowledge retention across a variety of technical topics.
 *
 * This File Contains the questions used in Dev Quiz.
 * It holds arrays of question objects, each representing a specific technical area.
 *
 * Each question object has the following structure:
 * - `id`: A unique identifier for the question.
 * - `topic`: The subject or category of the question (e.g., React, JavaScript, Node.js).
 * - `question`: The text of the question being asked.
 * - `language`: (Optional) A string indicating the programming language for code-related questions.
 * - `code`: (Optional) A boolean indicating if the question involves code.
 * - `options`: An array of possible answers, each with a `text` property and an optional `code` property.
 * - `answer`: The correct answer for the question.
 * - `explanation`: An explanation of why the answer is correct, with optional code examples.
 *
 * Topic covered in this file:
 * - JavaScript (Hoisting, Closures, Prototypes)
 */

export const javascriptQuestions = [
  // JAVASCRIPT — HOISTING & SCOPING (IDs 1–5)
  {
    id: 1,
    topic: "JavaScript",
    question: "What will this code output?",
    language: "javascript",
    code: `console.log(myVar);
var myVar = 5;`,
    options: [
      { text: "5", code: false },
      { text: "undefined", code: false },
      { text: "ReferenceError", code: false },
      { text: "null", code: false },
    ],
    answer: "undefined",
    explanation: {
      text: "Variable declarations with `var` are hoisted but not initialized. So `myVar` is `undefined` at the time of the `console.log`.",
      code: false,
    },
  },
  {
    id: 2,
    topic: "JavaScript",
    question: "What will this code output?",
    language: "javascript",
    code: `console.log(myVar);
let myVar = 5;`,
    options: [
      { text: "undefined", code: false },
      { text: "5", code: false },
      { text: "ReferenceError", code: false },
      { text: "null", code: false },
    ],
    answer: "ReferenceError",
    explanation: {
      text: "`let` and `const` are hoisted but not accessible before their declaration due to the temporal dead zone (TDZ).",
      code: false,
    },
  },
  {
    id: 3,
    topic: "JavaScript",
    question:
      "What is the scope of a variable declared using `var` inside a function?",
    code: false,
    language: false,
    options: [
      { text: "Block scope", code: false },
      { text: "Global scope", code: false },
      { text: "Function scope", code: false },
      { text: "Module scope", code: false },
    ],
    answer: "Function scope",
    explanation: {
      text: "`var` declarations are function-scoped, meaning they are only accessible within the function in which they are declared.",
      code: false,
    },
  },
  {
    id: 4,
    topic: "JavaScript",
    question: "Which variables are block-scoped?",
    code: false,
    language: false,
    options: [
      { text: "`var`", code: false },
      { text: "`let` and `const`", code: false },
      { text: "`const` only", code: false },
      { text: "`let` only", code: false },
    ],
    answer: "`let` and `const`",
    explanation: {
      text: "Both `let` and `const` are block-scoped, meaning they are only accessible within the block they are defined in.",
      code: false,
    },
  },
  {
    id: 5,
    topic: "JavaScript",
    question: "What is the result of this code?",
    language: "javascript",
    code: `function test() {
  if (true) {
    var x = 5;
  }
  console.log(x);
}
test();`,
    options: [
      { text: "undefined", code: false },
      { text: "ReferenceError", code: false },
      { text: "5", code: false },
      { text: "null", code: false },
    ],
    answer: "5",
    explanation: {
      text: "`var` is function-scoped, not block-scoped. So even though it's declared inside the `if` block, it's accessible in the rest of the function.",
      code: false,
    },
  },

  // JAVASCRIPT — FUNCTIONS (IDs 6–9)
  {
    id: 6,
    topic: "JavaScript",
    question:
      "What is the main difference between a function declaration and a function expression?",
    code: false,
    language: false,
    options: [
      {
        text: "Function expressions can be named, declarations can't",
        code: false,
      },
      { text: "Function declarations are hoisted", code: false },
      { text: "Function expressions are hoisted", code: false },
      { text: "Function declarations can’t access `this`", code: false },
    ],
    answer: "Function declarations are hoisted",
    explanation: {
      text: "Function declarations are hoisted and can be called before they appear in the code. Function expressions are not hoisted.",
      code: false,
    },
  },
  {
    id: 7,
    topic: "JavaScript",
    question: "What will this code output?",
    language: "javascript",
    code: `const add = (a, b) => {
  return a + b;
};
console.log(add(2, 3));`,
    options: [
      { text: "23", code: false },
      { text: "5", code: false },
      { text: "undefined", code: false },
      { text: "NaN", code: false },
    ],
    answer: "5",
    explanation: {
      text: "The arrow function returns the sum of the two numbers correctly.",
      code: false,
    },
  },
  {
    id: 8,
    topic: "JavaScript",
    question: "What is an IIFE (Immediately Invoked Function Expression)?",
    code: false,
    language: false,
    options: [
      { text: "A function that calls itself inside the body", code: false },
      { text: "A function defined in the global scope", code: false },
      { text: "A function that runs as soon as it is defined", code: false },
      { text: "A function that cannot be reused", code: false },
    ],
    answer: "A function that runs as soon as it is defined",
    explanation: {
      text: "An IIFE is a function that is executed immediately after it is created. It's commonly wrapped in parentheses to execute right away.",
      code: false,
    },
  },
  {
    id: 9,
    topic: "JavaScript",
    question: "What will this code log?",
    language: "javascript",
    code: `function outer() {
  const message = "Hello";
  function inner() {
    console.log(message);
  }
  return inner;
}
const sayHello = outer();
sayHello();`,
    options: [
      { text: `"Hello"`, code: false },
      { text: `"undefined"`, code: false },
      { text: `"message"`, code: false },
      { text: `ReferenceError`, code: false },
    ],
    answer: `"Hello"`,
    explanation: {
      text: "This is an example of a closure — `inner` still has access to the `message` variable from `outer`'s scope.",
      code: false,
    },
  },

  // JAVASCRIPT — ASYNC JS (IDs 10–14)

  {
    id: 10,
    topic: "JavaScript",
    question: "What does a Promise represent in JavaScript?",
    code: false,
    language: false,
    options: [
      { text: "A synchronous operation", code: false },
      {
        text: "A future value or eventual completion of an async operation",
        code: false,
      },
      { text: "A callback function", code: false },
      { text: "An immediately executed function", code: false },
    ],
    answer: "A future value or eventual completion of an async operation",
    explanation: {
      text: "A Promise represents a value that may be available now, or in the future, or never. It's used to handle asynchronous operations.",
      code: false,
    },
  },
  {
    id: 11,
    topic: "JavaScript",
    question: "What will this code log?",
    language: "javascript",
    code: `console.log("A");
setTimeout(() => console.log("B"), 0);
console.log("C");`,
    options: [
      { text: "A B C", code: false },
      { text: "A C B", code: false },
      { text: "C A B", code: false },
      { text: "B A C", code: false },
    ],
    answer: "A C B",
    explanation: {
      text: "`setTimeout` is asynchronous. The main thread logs A and C first. B is placed in the task queue and logs after.",
      code: false,
    },
  },
  {
    id: 12,
    topic: "JavaScript",
    question:
      "What keyword is used to pause code execution until a Promise resolves?",
    code: false,
    language: false,
    options: [
      { text: "await", code: false },
      { text: "pause", code: false },
      { text: "yield", code: false },
      { text: "defer", code: false },
    ],
    answer: "await",
    explanation: {
      text: "`await` is used with async functions to pause execution until the Promise is resolved or rejected.",
      code: false,
    },
  },
  {
    id: 13,
    topic: "JavaScript",
    question: "What will this code log?",
    language: "javascript",
    code: `async function fetchData() {
  return "Done";
}
fetchData().then(res => console.log(res));`,
    options: [
      { text: `"Done"`, code: false },
      { text: `undefined`, code: false },
      { text: `Promise`, code: false },
      { text: `ReferenceError`, code: false },
    ],
    answer: `"Done"`,
    explanation: {
      text: "`async` functions always return a Promise, which resolves to the returned value. Here, it resolves to 'Done'.",
      code: false,
    },
  },
  {
    id: 14,
    topic: "JavaScript",
    question:
      "Which part of the JavaScript runtime handles `setTimeout` callbacks?",
    code: false,
    language: false,
    options: [
      { text: "Call stack", code: false },
      { text: "Web APIs / Browser APIs", code: false },
      { text: "Promise queue", code: false },
      { text: "Heap", code: false },
    ],
    answer: "Web APIs / Browser APIs",
    explanation: {
      text: "Functions like `setTimeout` are handled by the browser environment (Web APIs) and placed in the callback queue when done.",
      code: false,
    },
  },

  // JAVASCRIPT — OBJECTS & ARRAYS (IDs 15–18)

  {
    id: 15,
    topic: "JavaScript",
    question: "What is the result of the following code?",
    language: "javascript",
    code: `const obj1 = { a: 1 };
const obj2 = obj1;
obj2.a = 2;
console.log(obj1.a);`,
    options: [
      { text: "1", code: false },
      { text: "2", code: false },
      { text: "undefined", code: false },
      { text: "ReferenceError", code: false },
    ],
    answer: "2",
    explanation: {
      text: "Objects are passed by reference in JavaScript. Changing `obj2.a` also changes `obj1.a` since both point to the same object.",
      code: false,
    },
  },
  {
    id: 16,
    topic: "JavaScript",
    question: "What is the spread operator used for in JavaScript?",
    code: false,
    language: false,
    options: [
      { text: "To convert a string to a number", code: false },
      { text: "To copy and expand arrays or objects", code: false },
      { text: "To create a Promise", code: false },
      { text: "To bind `this`", code: false },
    ],
    answer: "To copy and expand arrays or objects",
    explanation: {
      text: "The spread operator (`...`) is used to expand iterable values (like arrays or objects) into individual elements or properties.",
      code: false,
    },
  },
  {
    id: 17,
    topic: "JavaScript",
    question: "What will this code log?",
    language: "javascript",
    code: `const [a, b] = [1, 2, 3];
console.log(a, b);`,
    options: [
      { text: "1 2", code: false },
      { text: "1 3", code: false },
      { text: "undefined undefined", code: false },
      { text: "3 1", code: false },
    ],
    answer: "1 2",
    explanation: {
      text: "Destructuring assigns the first two values of the array to variables `a` and `b`.",
      code: false,
    },
  },
  {
    id: 18,
    topic: "JavaScript",
    question:
      "Which method creates a new array with only elements that pass a condition?",
    code: false,
    language: false,
    options: [
      { text: "map()", code: false },
      { text: "forEach()", code: false },
      { text: "filter()", code: false },
      { text: "reduce()", code: false },
    ],
    answer: "filter()",
    explanation: {
      text: "`filter()` returns a new array containing elements for which the callback returns `true`.",
      code: false,
    },
  },
  // JAVASCRIPT — DOM & BOM (IDs 19–21)

  {
    id: 19,
    topic: "JavaScript",
    question: 'What does `document.querySelector(".my-class")` return?',
    code: false,
    language: false,
    options: [
      { text: "A NodeList of matching elements", code: false },
      { text: "An array of elements with the class 'my-class'", code: false },
      { text: "The first element that matches the selector", code: false },
      { text: "null if no element is found", code: false },
    ],
    answer: "The first element that matches the selector",
    explanation: {
      text: "`querySelector()` returns the first element that matches the given CSS selector. Use `querySelectorAll()` for a NodeList of all matches.",
      code: false,
    },
  },
  {
    id: 20,
    topic: "JavaScript",
    question:
      "Which of the following methods is used to attach an event listener to a DOM element?",
    code: false,
    language: false,
    options: [
      { text: "addEvent()", code: false },
      { text: "onEvent()", code: false },
      { text: "addEventListener()", code: false },
      { text: "attachEvent()", code: false },
    ],
    answer: "addEventListener()",
    explanation: {
      text: "`addEventListener()` is the modern method for registering event handlers on DOM elements.",
      code: false,
    },
  },
  {
    id: 21,
    topic: "JavaScript",
    question: "What is the purpose of `window.setInterval()`?",
    code: false,
    language: false,
    options: [
      { text: "To run code after a delay", code: false },
      {
        text: "To execute a function repeatedly at a specified interval",
        code: false,
      },
      { text: "To create a loop", code: false },
      { text: "To run code once when the page loads", code: false },
    ],
    answer: "To execute a function repeatedly at a specified interval",
    explanation: {
      text: "`setInterval()` repeatedly calls a function with a fixed time delay between each call, until cleared with `clearInterval()`.",
      code: false,
    },
  },

  // JAVASCRIPT — THIS / CALL / APPLY / BIND (IDs 22–24)

  {
    id: 22,
    topic: "JavaScript",
    question:
      "What does `this` refer to inside a regular function (not an arrow function) in non-strict mode?",
    code: false,
    language: false,
    options: [
      { text: "The global object (e.g. `window`)", code: false },
      { text: "undefined", code: false },
      { text: "The function itself", code: false },
      { text: "The object that called it", code: false },
    ],
    answer: "The global object (e.g. `window`)",
    explanation: {
      text: "In non-strict mode, regular functions default `this` to the global object if not called as a method.",
      code: false,
    },
  },
  {
    id: 23,
    topic: "JavaScript",
    question:
      "Which method allows you to call a function with a specific `this` value and arguments as an array?",
    code: false,
    language: false,
    options: [
      { text: "call()", code: false },
      { text: "apply()", code: false },
      { text: "bind()", code: false },
      { text: "spread()", code: false },
    ],
    answer: "apply()",
    explanation: {
      text: "`apply()` is used to invoke a function with a specified `this` and arguments passed as an array.",
      code: false,
    },
  },
  {
    id: 24,
    topic: "JavaScript",
    question: "What does the `bind()` method return?",
    code: false,
    language: false,
    options: [
      {
        text: "A function that calls the original function immediately",
        code: false,
      },
      { text: "A new function with permanently bound `this`", code: false },
      { text: "An object", code: false },
      { text: "A reference to the original function", code: false },
    ],
    answer: "A new function with permanently bound `this`",
    explanation: {
      text: "`bind()` returns a new function with a fixed `this` value, without calling the original function immediately.",
      code: false,
    },
  },

  // JAVASCRIPT — TYPE COERCION (IDs 25–27)

  {
    id: 25,
    topic: "JavaScript",
    question: "What is the result of `'5' + 2`?",
    code: false,
    language: false,
    options: [
      { text: `"7"`, code: false },
      { text: `"52"`, code: false },
      { text: `7`, code: false },
      { text: `NaN`, code: false },
    ],
    answer: `"52"`,
    explanation: {
      text: "In JavaScript, the `+` operator with a string and number triggers string concatenation.",
      code: false,
    },
  },
  {
    id: 26,
    topic: "JavaScript",
    question:
      "Which of the following values is loosely equal (`==`) to `false`?",
    code: false,
    language: false,
    options: [
      { text: `"0"`, code: false },
      { text: `"false"`, code: false },
      { text: `"null"`, code: false },
      { text: `"undefined"`, code: false },
    ],
    answer: `"0"`,
    explanation: {
      text: "`'0' == false` is true due to type coercion. JavaScript converts both to numbers before comparing.",
      code: false,
    },
  },
  {
    id: 27,
    topic: "JavaScript",
    question: "Which operator does NOT trigger type coercion?",
    code: false,
    language: false,
    options: [
      { text: `"=="`, code: false },
      { text: `"+"`, code: false },
      { text: `"==="`, code: false },
      { text: `"!="`, code: false },
    ],
    answer: `"==="`,
    explanation: {
      text: "`===` (strict equality) checks both type and value, and does NOT perform type coercion.",
      code: false,
    },
  },

  // JAVASCRIPT — PROTOTYPES (IDs 28–30)

  {
    id: 28,
    topic: "JavaScript",
    question: "What is the prototype chain?",
    code: false,
    language: false,
    options: [
      { text: "A list of all properties of an object", code: false },
      {
        text: "A mechanism to inherit properties from other objects",
        code: false,
      },
      { text: "A way to bind functions", code: false },
      { text: "A loop of function calls", code: false },
    ],
    answer: "A mechanism to inherit properties from other objects",
    explanation: {
      text: "The prototype chain allows objects to inherit methods and properties from their prototype.",
      code: false,
    },
  },
  {
    id: 29,
    topic: "JavaScript",
    question: "What is the prototype of an object created via `{}`?",
    code: false,
    language: false,
    options: [
      { text: "null", code: false },
      { text: "Function.prototype", code: false },
      { text: "Object.prototype", code: false },
      { text: "Array.prototype", code: false },
    ],
    answer: "Object.prototype",
    explanation: {
      text: "`{}` creates a plain object whose prototype is `Object.prototype`.",
      code: false,
    },
  },
  {
    id: 30,
    topic: "JavaScript",
    question: "What will this code log?",
    language: "javascript",
    code: `function Person(name) {
  this.name = name;
}
Person.prototype.greet = function () {
  return "Hello " + this.name;
};
const user = new Person("Ema");
console.log(user.greet());`,
    options: [
      { text: `"Hello Ema"`, code: false },
      { text: `"undefined"`, code: false },
      { text: `TypeError`, code: false },
      { text: `"Hello"`, code: false },
    ],
    answer: `"Hello Ema"`,
    explanation: {
      text: "The method `greet()` is available via the prototype chain. It uses `this.name` from the instance `user`.",
      code: false,
    },
  },

  // JAVASCRIPT — MISCELLANEOUS (IDs 31–33)

  {
    id: 31,
    topic: "JavaScript",
    question: "What does `typeof NaN` return?",
    code: false,
    language: false,
    options: [
      { text: `"number"`, code: false },
      { text: `"NaN"`, code: false },
      { text: `"undefined"`, code: false },
      { text: `"object"`, code: false },
    ],
    answer: `"number"`,
    explanation: {
      text: "`typeof NaN` returns 'number'. This is a well-known quirk in JavaScript.",
      code: false,
    },
  },
  {
    id: 32,
    topic: "JavaScript",
    question: "What does `Object.freeze()` do?",
    code: false,
    language: false,
    options: [
      { text: "Makes an object immutable", code: false },
      { text: "Deletes all object keys", code: false },
      { text: "Prevents iteration over properties", code: false },
      { text: "Turns the object into a primitive", code: false },
    ],
    answer: "Makes an object immutable",
    explanation: {
      text: "`Object.freeze()` prevents new properties from being added, and existing properties from being changed or deleted.",
      code: false,
    },
  },
  {
    id: 33,
    topic: "JavaScript",
    question:
      "Which global object provides methods for encoding and decoding base64 strings?",
    code: false,
    language: false,
    options: [
      { text: "JSON", code: false },
      { text: "B64", code: false },
      { text: "Base64", code: false },
      { text: "window", code: false },
    ],
    answer: "window",
    explanation: {
      text: "`window.atob()` and `window.btoa()` can be used to decode and encode base64 strings in the browser.",
      code: false,
    },
  },

  // JAVASCRIPT — CODE OUTPUT & ERROR SPOTTING (IDs 34–39)

  {
    id: 34,
    topic: "JavaScript",
    question: "What will this code output?",
    language: "javascript",
    code: `let a = 10;
(function() {
  console.log(a);
  let a = 5;
})();`,
    options: [
      { text: `"10"`, code: false },
      { text: `"5"`, code: false },
      { text: `undefined`, code: false },
      { text: `ReferenceError`, code: false },
    ],
    answer: "ReferenceError",
    explanation: {
      text: "Due to `let`'s temporal dead zone, `a` is hoisted but not initialized. Accessing it before declaration throws a ReferenceError.",
      code: false,
    },
  },
  {
    id: 35,
    topic: "JavaScript",
    question: "What will this code log?",
    language: "javascript",
    code: `const obj = {
  message: "Hello",
  logMessage: function () {
    console.log(this.message);
  },
};
setTimeout(obj.logMessage, 100);`,
    options: [
      { text: `"Hello"`, code: false },
      { text: `"undefined"`, code: false },
      { text: `"logMessage"`, code: false },
      { text: `TypeError`, code: false },
    ],
    answer: `"undefined"`,
    explanation: {
      text: "`setTimeout(obj.logMessage)` detaches the method from the object. `this` becomes `window` (or `undefined` in strict mode), so `this.message` is `undefined`.",
      code: false,
    },
  },
  {
    id: 36,
    topic: "JavaScript",
    question: "What is the result of this code?",
    language: "javascript",
    code: `const result = [] + 1 + 2;
console.log(result);`,
    options: [
      { text: `"3"`, code: false },
      { text: `"12"`, code: false },
      { text: `"undefined"`, code: false },
      { text: `TypeError`, code: false },
    ],
    answer: `"12"`,
    explanation: {
      text: '`[] + 1` results in `"1"`, then `"1" + 2` becomes `"12"`. JavaScript coerces values to strings when using `+` with arrays.',
      code: false,
    },
  },
  {
    id: 37,
    topic: "JavaScript",
    question: "What will this code print?",
    language: "javascript",
    code: `for (var i = 0; i < 3; i++) {
  setTimeout(() => console.log(i), 0);
}`,
    options: [
      { text: `"0", "1", "2"`, code: false },
      { text: `"3", "3", "3"`, code: false },
      { text: `"0", "1", "2", "3"`, code: false },
      { text: `"undefined", "undefined", "undefined"`, code: false },
    ],
    answer: `"3", "3", "3"`,
    explanation: {
      text: "Due to `var` being function-scoped, all timeouts share the same `i`, which becomes 3 after the loop ends.",
      code: false,
    },
  },
  {
    id: 38,
    topic: "JavaScript",
    question: "What happens when you run this?",
    language: "javascript",
    code: `let x = 1;
x();`,
    options: [
      { text: `"1"`, code: false },
      { text: `TypeError`, code: false },
      { text: `ReferenceError`, code: false },
      { text: `"x()"`, code: false },
    ],
    answer: "TypeError",
    explanation: {
      text: "`x` is a number, not a function. Calling a non-function like `x()` throws a TypeError.",
      code: false,
    },
  },
  {
    id: 39,
    topic: "JavaScript",
    question: "What is the result of the following code?",
    language: "javascript",
    code: `console.log(typeof null);`,
    options: [
      { text: `"null"`, code: false },
      { text: `"object"`, code: false },
      { text: `"undefined"`, code: false },
      { text: `"NaN"`, code: false },
    ],
    answer: `"object"`,
    explanation: {
      text: "`typeof null` returns `'object'`. This is a long-standing bug in JavaScript that remains for legacy reasons.",
      code: false,
    },
  },
];
